### PR TITLE
Add generated response model objects.

### PR DESCRIPTION
**Pull request by drhaynes**
For discussion. Response model objects as generated by https://github.com/insanoid/SwiftyJSONAccelerator

Thinking we can probably remove the dictionary representation methods.

The way the model has been approached on Android is to bury all of this behind an object that only exposes the fields we are interested in.

### CODE REVIEW

**Comment by drhaynes** [comment]
Now with updated generated model objects, as per: https://github.com/insanoid/SwiftyJSONAccelerator/pull/13

**Comment by drhaynes** [comment]
Also wondering about test coverage on these...

**Comment by dhardiman** [comment]
Test coverage should come when you actually write some code to throw data at the model objects. Looks good. There's lots of optional properties still, but that doesn't frighten me from merging this if you're happy, but we should make sure they get audited as you start fetching data. Non-optional by default might be a nicer place to start though?

**Comment by drhaynes** [comment]
Yes, agree that non-optional by default is better. Will update.

**Comment by drhaynes** [comment]
Bump

**Pull request merged**
